version: '3.7'

services:
  main:
    container_name: back
    build:
      context: ./back
      target: development
    links:
       - "postgres"
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    env_file:
      - env
    environment:
      - POSTGRES=postgres
    networks:
      - webnet
    depends_on:
      - postgres
  phppgadmin:
    container_name: phppgadmin
    image: neimheadh/phppgadmin:latest
    ports:
      - "8000:80"
    links:
      - "postgres"
    env_file:
      - env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASS=password
    networks: 
      - webnet
    depends_on:
      - postgres
    
  postgres:
    container_name: postgres
    image: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: ft_transcendance
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  front:
    container_name: front-vue
    build:
      context: ./front
      target: development
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:8080
      - 9228:9228
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run serve
    networks:
      - webnet
    depends_on:
      - main
networks:
  webnet:
volumes:
  pgdata: